CREATDATA DATABASE PBK;
CREATE TABLE Guru (
	id INT(11) UNSIGNED AUTO_INCREMENT;
	Nama VARCHAR (40) NOT NULL;
	Level INT(1) NOT NULL;
	E-mail VARCHAR(40) NOT NULL;
	Password VARCHAR(30) NOT NULL;
	PRIMARY KEY (id);
)
 
CREATE TABLE Pelajaran (
	id_Pelajaran INT(11) UNSIGNED AUTO_INCREMENT;
	Nama VARCHAR (40) NOT NULL;
	PRIMARY KEY (id_Pelajaran);
)
CREATE TABLE Materi(
	id_Materi INT(11) UNSIGNED AUTO_INCREMENT;
	Nama VARCHAR(40) NOT NULL;
	Guru VARCHAR(40) NOT NULL;  
	PRIMARY KEY (id_Materi);
)
